feign:
  hystrix:
    enabled: false

logging:
  level:
    com:
      som:
        incomestatement:
          client:
            TransactionsApi: DEBUG

capitalone:
  url: https://2016.api.levelmoney.com/api/v2/core/

filter:
  transaction:
    ignore-donuts: "Krispy Kreme Donuts,DUNKIN #336784"

